### ISSUE TITLE
Problema instalación agora-results

### ISSUE THREAD

**Issue by Joseda13** [EGC-AgoraResultsTest/agora-results-tests#1]
Siguiendo la documentación de instalación de "Agora-Results", del proyecto Agora-Voting se produce el siguiente problema: 

Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-j_nvc6jj-build/setup.py", line 11, in <module>
        reqs = [str(ir.req) for ir in install_reqs]
      File "/tmp/pip-j_nvc6jj-build/setup.py", line 11, in <listcomp>
        reqs = [str(ir.req) for ir in install_reqs]
      File "/home/gaems-dev/.virtualenvs/agora-results/lib/python3.4/site-packages/pip/req/req_file.py", line 72, in parse_requirements
        "parse_requirements() missing 1 required keyword argument: "
    TypeError: parse_requirements() missing 1 required keyword argument: 'session'

Cuando intentamos ejecutar el siguiente comando: 

pip install git+https://github.com/agoravoting/agora-results.git

**Comment by DrXoo** [comment]
Siguiendo la ruta del error en : /home/gaems-dev/.virtualenvs/agora-results/lib/python3.4/site-packages/pip/req/req_file.py

Observamos que ese archivo es quien está dando el error, centrado en la función parse_requirements(). El error se produce cuando el argumento de entrada "session" es nulo.

**Comment by DrXoo** [comment]
Se ha solucionado este error haciendo que el argumento "session" sea "False".
