### ISSUE TITLE
Problemas al clonar el repositorio agora-results

### ISSUE THREAD

**Issue by Joseda13** [EGC-AgoraResultsTest/agora-results-tests#2]
Una vez instalado el entorno de trabajo en el que se utilizará agora-results, cuando se intenta clonar el repositorio en nuestro entorno de trabajo sucede el error que se muestra en la siguiente captura de pantalla:
![screenshot - 251115 - 11 58 56](https://cloud.githubusercontent.com/assets/15341374/11500698/0ab1ea0a-982f-11e5-9d76-6dba1b9a8ba4.png)

**Comment by DrXoo** [comment]
Este error se debe a que el archivo de dependencias requeridas no está actuando correctamente.

Para solucionar este error debemos modificar el comando de instalación (clonado) de agora-results:

pip install git+https://github.com/agoravoting/agora-results.git –r requisitos.txt

El archivo "requisitos.txt" está adjuntado en esta respuesta para que sirva de solución. 

[requisitos.txt](https://github.com/EGC-AgoraResultsTest/agora-results-tests/files/48497/requisitos.txt)
