### ISSUE TITLE
Problema al ejecutar el comando agora-result

### ISSUE THREAD

**Issue by DrXoo** [EGC-AgoraResultsTest/agora-results-tests#3]
Al ejecutar el comando agora-result utilizando un tally de ejemplo se produce un error de código en algunas clases que se hace una llamada errónea al no existir un plugin o librería concreta. 

Adjunto dejo algunas imágenes para mayor comprensión del error y que puedan dar alguna pista para su solución.

![screenshot - 251115 - 13_00_43](https://cloud.githubusercontent.com/assets/15670575/11500896/608e8d42-9830-11e5-97e6-ae2ec4a2ab92.png)
![screenshot - 251115 - 13_00_52](https://cloud.githubusercontent.com/assets/15670575/11500895/608e44a4-9830-11e5-99cd-c2d6b4198fd2.png)

**Comment by Joseda13** [comment]
Tras seguir la traza se ha concluido que el problema estaba al aplicar el fichero requirements.txt, en el que estaban estas líneas:

-e git+https://github.com/agoravoting/openstv.git@next#egg=openstv
-e git+https://github.com/agoravoting/agora-tally.git@next#egg=agora-tally

La solución es cambiarlas por las siguientes:

-e git+https://github.com/agoravoting/openstv.git@master#egg=openstv
-e git+https://github.com/agoravoting/agora-tally.git@master#egg=agora-tally
