### ISSUE TITLE
Fallo con el uso de pybuilder

### ISSUE THREAD

**Issue by Joseda13** [EGC-AgoraResultsTest/agora-results-tests#4]
Cuando he intentado ejecutar pybuilder dentro del proyecto, después de seguir las instrucciones del archivo README me ha salido el siguiente error:
![virtualbox_gaems-developer_01_12_2015_17_53_05](https://cloud.githubusercontent.com/assets/15341374/11507475/8127ae2a-9854-11e5-803a-d4b872c64415.png)

**Comment by DrXoo** [comment]
Al ser un proyecto importado es normal que salga esto, parece que has instalado el PyBuilder pero faltan las dependencias. 

prueba a poner : pyb install_dependencies

**Comment by Joseda13** [comment]
He introducido dicho comando en la terminal y ahora funciona correctamente.

**Comment by DrXoo** [comment]
Se procederá a modificar el README.md para incluir esta información.
