### ISSUE TITLE
Error al ejecutar comandos Python en Jenkins bajo un VirtualEnv

### ISSUE THREAD

**Issue by Joseda13** [EGC-AgoraResultsTest/agora-results-tests#8]
Encontrado error a la hora de intentar ejecutar comandos en un entorno virtual (VirtualEnv) dentro de Jenkins. El error es el siguiente:

FATAL: invalid interpreter: /usr/lib/python3.4/

**Comment by DrXoo** [comment]
La ruta era errónea, ya que se pedía la ruta al comando ejecutable de python. La ruta correcta es:

/usr/bin/python3.4

Esta modificación se debe de realizar en la configuración de Jenkins, en la sección de instalaciones de Python.

**Comment by Joseda13** [comment]
OK
